### ISSUE TITLE
How far from a ready to use version? 

### ISSUE THREAD

**Issue by sletz** [Kutalia/react-webaudio-5150#2]
We maintain a list of applications using Faust here: https://faust.grame.fr/community/made-with-faust/
How far is the react-webaudio-5150 project to be stable enough to be advertised here ?

**Comment by Kutalia** [comment]
The project is already quite stable. I am planning to add new features like better GUI and sound options in a framework of a month or two. It would be my honor if my work got displayed on the official FAUST webpage.

**Comment by sletz** [comment]
OK great! do you have a screenshot to share? And do you have a short explanation on how Faust is used ? (possibly simply completing the README file ?) Thanks.

**Comment by Kutalia** [comment]
I have updated README.md on your request. It now includes short description and a screenshot.

**Comment by sletz** [comment]
Thanks a lot: added here https://faust.grame.fr/community/made-with-faust/#react-web-audio-guitar-studio

**Comment by micbuffa** [comment]
Hi! I'd like exchange with you as with a group of other people who have been working on a plugin standard for WebAudio. I also wrote several tube amp sim simulations + ported oleg's plugins to our plugin format. The Faust IDE is ready with all the tools, including a GUI builder and plugin exporter or this format (WebAudioModules v2). We also have react projects (host and plugins). It would be very cool if you could join us... I'd also like to share with you about guitar effects and simulations.
Michel Buffa
PS: see the presentation of the WAM2 standard we gave at the last WebAudio Conference: https://www.youtube.com/watch?v=8G3we8dikq8, see also my YT channel (look for "webaudio guitar amp simulator", you will find my channel...). 
Michel
